### ISSUE TITLE
機能一覧

### ISSUE THREAD

**Issue by sako590829** [sako590829/graduation-work#3]
【ログイン】
＃概要
勤務希望を集約するにあたって誰が入力したものなのかを判別するもの。
＃完了条件
ID及びパスワードを入力することでユーザーが判別できるようになること。

【勤務希望集約】
＃概要
ユーザーが勤務希望を入力し、全社員分を集約するためのもの。
＃完了条件
毎月１８日０：００に全社員分がｘｘに集約されるようになること。

【自動作成】
＃概要
勤務条件に基づき、勤務を作成すること
＃完了条件
自動作成の上Excelベースで出力できるようになること

【勤務データ管理】
＃概要
過去の勤務データを蓄積する
＃毎月月末最終日段階の勤務表を毎月１日０：００の段階で蓄積できるようにすること

**Comment by technicakidz** [comment]
それぞれを issue にしたのでクローズします。
